#!/usr/bin/env bash
# Deploy batchalign3 CLI to client machines alongside batchalign-next (coexistence).
#
# Builds a wheel from the batchalign3 repo (Python 3.12), deploys to clients.
# Creates server.yaml with port 8001 so the auto-daemon doesn't collide with
# batchalign-next on port 8000.
#
# Usage:
#   bash scripts/deploy_batchalign3_clients.sh              # all clients
#   bash scripts/deploy_batchalign3_clients.sh bilbo study   # specific hosts
#   bash scripts/deploy_batchalign3_clients.sh --no-build    # skip wheel build
#   bash scripts/deploy_batchalign3_clients.sh --dry-run     # show plan only

set -euo pipefail

SSH_USER="macw"
ALL_HOSTS=(bilbo brian davida frodo andrew lilly sue vaishnavi)
PORT=8001  # Coexistence: batchalign-next keeps 8000

WORKSPACE_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BA3_REPO="$WORKSPACE_ROOT/batchalign3"

DRY_RUN=false
NO_BUILD=false

HOSTS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)   DRY_RUN=true; shift ;;
        --no-build)  NO_BUILD=true; shift ;;
        --help|-h)
            echo "Usage: bash scripts/deploy_batchalign3_clients.sh [OPTIONS] [HOST...]"
            echo ""
            echo "Options:"
            echo "  --no-build   Skip wheel build"
            echo "  --dry-run    Show plan only"
            exit 0
            ;;
        *) HOSTS+=("$1"); shift ;;
    esac
done

if [[ ${#HOSTS[@]} -eq 0 ]]; then
    HOSTS=("${ALL_HOSTS[@]}")
fi

if [[ ! -f "$BA3_REPO/pyproject.toml" ]]; then
    echo "ERROR: batchalign3 repo not found at $BA3_REPO"
    exit 1
fi

# --- Build wheel ---

if ! $NO_BUILD; then
    echo "=== Building wheel ==="
    (cd "$BA3_REPO" && uv build --wheel --out-dir dist/ 2>&1 | tail -3)
    echo ""
fi

WHEEL="$(ls -t "$BA3_REPO"/dist/batchalign3-*.whl 2>/dev/null | head -1)"

if [[ -z "$WHEEL" || ! -f "$WHEEL" ]]; then
    echo "ERROR: No wheel found in $BA3_REPO/dist/"
    echo "Run without --no-build to build a fresh wheel."
    exit 1
fi

WHEEL_NAME="$(basename "$WHEEL")"

echo "Deploying batchalign3 to clients: ${HOSTS[*]}"
echo "  wheel: $WHEEL_NAME"
echo ""

if $DRY_RUN; then
    echo "=== DRY RUN — no changes made ==="
    exit 0
fi

# --- Deploy ---

SUCCESSES=0
FAILURES=0

for host in "${HOSTS[@]}"; do
    echo "=== $host ==="

    if ! ssh -o ConnectTimeout=5 "$SSH_USER@$host" true 2>/dev/null; then
        echo "  SKIP: cannot connect"
        FAILURES=$((FAILURES + 1))
        echo ""
        continue
    fi

    scp -q "$WHEEL" "$SSH_USER@$host:/tmp/$WHEEL_NAME"

    # Stop batchalign3 daemons only (leave batchalign-next alone)
    ssh "$SSH_USER@$host" '
        batchalign3 serve stop 2>/dev/null || true
        pkill -9 -f "batchalign3 serve" 2>/dev/null || true
    ' 2>/dev/null || true

    echo "  Installing..."
    ssh "$SSH_USER@$host" "
        uv tool uninstall batchalign3 2>/dev/null || true
        uv tool install --python 3.12 --force-reinstall /tmp/$WHEEL_NAME 2>&1
    " | tail -3

    # server.yaml with port 8001 (auto-daemon coexistence)
    ssh "$SSH_USER@$host" "
        mkdir -p \$HOME/.batchalign3
        CONFIG=\$HOME/.batchalign3/server.yaml
        if [ ! -f \"\$CONFIG\" ]; then
            cat > \"\$CONFIG\" <<YAML
# Auto-generated by deploy_batchalign3_clients.sh
default_lang: eng
port: $PORT
YAML
        else
            if grep -q '^port:' \"\$CONFIG\"; then
                sed -i '' 's/^port:.*/port: $PORT/' \"\$CONFIG\"
            else
                echo 'port: $PORT' >> \"\$CONFIG\"
            fi
        fi
    "

    ver=$(ssh "$SSH_USER@$host" 'batchalign3 version 2>&1' || echo "FAILED")
    echo "  $ver"

    if [[ "$ver" == *"FAILED"* ]]; then
        echo "  WARNING: verification failed"
        FAILURES=$((FAILURES + 1))
    else
        echo "  OK"
        SUCCESSES=$((SUCCESSES + 1))
    fi

    ssh "$SSH_USER@$host" "rm -f /tmp/$WHEEL_NAME" 2>/dev/null || true
    echo ""
done

echo "==============================="
echo "Done: $SUCCESSES ok, $FAILURES failed"
echo "==============================="
