#!/usr/bin/env bash
# Deploy batchalign3 server alongside batchalign-next (coexistence).
#
# Builds a wheel from the batchalign3 repo (Python 3.12), deploys to server
# machines, and starts on port 8001 so batchalign-next keeps port 8000.
#
# Usage:
#   bash scripts/deploy_batchalign3_server.sh              # deploy to Net
#   bash scripts/deploy_batchalign3_server.sh bilbo brian   # specific hosts
#   bash scripts/deploy_batchalign3_server.sh --all         # all fleet machines
#   bash scripts/deploy_batchalign3_server.sh --port 8000   # take over production port
#   bash scripts/deploy_batchalign3_server.sh --no-build    # skip wheel build
#   bash scripts/deploy_batchalign3_server.sh --dry-run     # show plan only

set -euo pipefail

SSH_USER="macw"
DEFAULT_HOST="net"
ALL_FLEET_HOSTS=(net bilbo brian davida frodo andrew lilly sue vaishnavi)
PORT=8001  # Coexistence: batchalign-next keeps 8000

WORKSPACE_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BA3_REPO="$WORKSPACE_ROOT/batchalign3"

DRY_RUN=false
NO_BUILD=false
DEPLOY_ALL=false

HOSTS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)   DRY_RUN=true; shift ;;
        --no-build)  NO_BUILD=true; shift ;;
        --all)       DEPLOY_ALL=true; shift ;;
        --port)      PORT="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: bash scripts/deploy_batchalign3_server.sh [OPTIONS] [HOST...]"
            echo ""
            echo "Options:"
            echo "  --all        Deploy to all fleet machines"
            echo "  --port PORT  Server port (default: 8001 for coexistence)"
            echo "  --no-build   Skip wheel build"
            echo "  --dry-run    Show plan only"
            exit 0
            ;;
        *) HOSTS+=("$1"); shift ;;
    esac
done

if $DEPLOY_ALL; then
    HOSTS=("${ALL_FLEET_HOSTS[@]}")
elif [[ ${#HOSTS[@]} -eq 0 ]]; then
    HOSTS=("$DEFAULT_HOST")
fi

if [[ ! -f "$BA3_REPO/pyproject.toml" ]]; then
    echo "ERROR: batchalign3 repo not found at $BA3_REPO"
    exit 1
fi

# --- Build wheel ---

if ! $NO_BUILD; then
    echo "=== Building wheel ==="
    (cd "$BA3_REPO" && uv build --wheel --out-dir dist/ 2>&1 | tail -3)
    echo ""
fi

WHEEL="$(ls -t "$BA3_REPO"/dist/batchalign3-*.whl 2>/dev/null | head -1)"

if [[ -z "$WHEEL" || ! -f "$WHEEL" ]]; then
    echo "ERROR: No wheel found in $BA3_REPO/dist/"
    echo "Run without --no-build to build a fresh wheel."
    exit 1
fi

WHEEL_NAME="$(basename "$WHEEL")"

echo "Deploying batchalign3 to: ${HOSTS[*]}  (port $PORT)"
echo "  wheel: $WHEEL_NAME"
echo ""

if $DRY_RUN; then
    echo "=== DRY RUN — no changes made ==="
    exit 0
fi

# --- Deploy ---

FAILED=()
OK=()

for host in "${HOSTS[@]}"; do
    echo ""
    echo "=== $host ==="

    if ! ssh -o ConnectTimeout=5 "$SSH_USER@$host" true 2>/dev/null; then
        echo "  SKIP: cannot connect"
        FAILED+=("$host")
        continue
    fi

    scp -q "$WHEEL" "$SSH_USER@$host:/tmp/$WHEEL_NAME"

    # Stop batchalign3 only (leave batchalign-next alone)
    echo "  Stopping batchalign3..."
    ssh "$SSH_USER@$host" '
        batchalign3 serve stop 2>/dev/null || true
        sleep 1
        pkill -9 -f "batchalign3 serve" 2>/dev/null || true
    ' 2>/dev/null || true

    echo "  Installing..."
    ssh "$SSH_USER@$host" "
        uv tool uninstall batchalign3 2>/dev/null || true
        uv tool install --python 3.12 --force-reinstall /tmp/$WHEEL_NAME 2>&1
    " | tail -3

    ver=$(ssh "$SSH_USER@$host" 'batchalign3 version 2>&1' || echo "FAILED")
    echo "  Version: $ver"

    if [[ "$ver" == "FAILED" ]]; then
        echo "  ERROR: batchalign3 not working"
        FAILED+=("$host")
        continue
    fi

    # server.yaml
    echo "  Configuring (port $PORT)..."
    ssh "$SSH_USER@$host" "
        mkdir -p \$HOME/.batchalign3
        CONFIG=\$HOME/.batchalign3/server.yaml
        if [ ! -f \"\$CONFIG\" ]; then
            cat > \"\$CONFIG\" <<YAML
# Auto-generated by deploy_batchalign3_server.sh
default_lang: eng
port: $PORT
warmup: true
job_ttl_days: 7
max_concurrent_jobs: 0
YAML
        else
            if grep -q '^port:' \"\$CONFIG\"; then
                sed -i '' 's/^port:.*/port: $PORT/' \"\$CONFIG\"
            else
                echo 'port: $PORT' >> \"\$CONFIG\"
            fi
        fi
    "

    echo "  Starting server..."
    ssh "$SSH_USER@$host" 'batchalign3 serve start'

    # Health check
    echo "  Waiting for health..."
    elapsed=0
    health=""
    while [ "$elapsed" -lt 180 ]; do
        sleep 5
        elapsed=$((elapsed + 5))
        health=$(ssh "$SSH_USER@$host" "curl -s http://localhost:$PORT/health 2>/dev/null" || echo '{}')
        if echo "$health" | grep -q '"status":"ok"'; then
            echo "  OK: healthy after ${elapsed}s"
            break
        fi
        printf "    %ds/180s...\r" "$elapsed"
    done

    if ! echo "$health" | grep -q '"status":"ok"'; then
        echo "  WARNING: health check failed"
        echo "  Logs: ssh $SSH_USER@$host 'tail -50 ~/.batchalign3/server.log'"
        FAILED+=("$host")
        continue
    fi

    ssh "$SSH_USER@$host" "rm -f /tmp/$WHEEL_NAME" 2>/dev/null || true
    OK+=("$host")
done

echo ""
echo "==============================="
if [[ ${#FAILED[@]} -eq 0 ]]; then
    echo "SUCCESS: ${#OK[@]} server(s) on port $PORT"
else
    echo "PARTIAL: ${#OK[@]} ok, ${#FAILED[@]} failed (${FAILED[*]})"
fi
echo "==============================="

[[ ${#FAILED[@]} -eq 0 ]]
