#!/usr/bin/env python3
"""Set up mergerfs union mounts for John's data app on talkbank.org.

Creates a flat /var/data/view/{bank}/ view for each of the 16 banks,
merging split repos transparently. John's app reads from /var/data/view/
and sees a single directory tree per bank regardless of how many repos
back it.

Prerequisites:
    sudo apt install mergerfs
    All 24 data repos cloned in /home/macw/data/

Usage:
    sudo python3 setup_mergerfs_views.py mount      # mount all
    sudo python3 setup_mergerfs_views.py unmount     # unmount all
    sudo python3 setup_mergerfs_views.py status      # show mount status
    sudo python3 setup_mergerfs_views.py fstab       # print fstab entries
"""

import argparse
import subprocess
from pathlib import Path

REPOS_ROOT = Path("/home/macw/data")
VIEW_ROOT = Path("/var/data/view")
MERGERFS_OPTS = (
    "defaults,allow_other,use_ino,"
    "cache.files=off,dropcacheonclose=true,category.create=mfs"
)

# Bank-to-repos mapping. Unsplit banks have one repo, split banks have 2-4.
# Order matters for mergerfs priority (first listed = highest priority for conflicts).
BANK_REPOS: dict[str, list[str]] = {
    # Unsplit banks (12)
    "aphasia": ["aphasia-data"],
    "asd": ["asd-data"],
    "biling": ["biling-data"],
    "class": ["class-data"],
    "dementia": ["dementia-data"],
    "fluency": ["fluency-data"],
    "motor": ["motor-data"],
    "psychosis": ["psychosis-data"],
    "rhd": ["rhd-data"],
    "samtale": ["samtale-data"],
    "slabank": ["slabank-data"],
    "tbi": ["tbi-data"],
    # Split banks (4)
    "ca": ["ca-candor-data", "ca-data"],
    "childes": [
        "childes-eng-na-data",
        "childes-eng-uk-data",
        "childes-romance-germanic-data",
        "childes-other-data",
    ],
    "homebank": [
        "homebank-public-data",
        "homebank-cougar-data",
        "homebank-bergelson-data",
        "homebank-password-data",
    ],
    "phon": ["phon-eng-french-data", "phon-other-data"],
}


def is_mounted(path: Path) -> bool:
    result = subprocess.run(
        ["mountpoint", "-q", str(path)],
        capture_output=True,
    )
    return result.returncode == 0


def sources_string(repos: list[str]) -> str:
    return ":".join(str(REPOS_ROOT / repo) for repo in repos)


def do_mount() -> None:
    print("Mounting mergerfs views...")
    VIEW_ROOT.mkdir(parents=True, exist_ok=True)

    mounted = 0
    skipped = 0

    for bank in sorted(BANK_REPOS):
        repos = BANK_REPOS[bank]
        mountpoint = VIEW_ROOT / bank
        mountpoint.mkdir(parents=True, exist_ok=True)

        if is_mounted(mountpoint):
            print(f"  {bank}: already mounted")
            skipped += 1
            continue

        # Verify all source repos exist
        missing = [r for r in repos if not (REPOS_ROOT / r).is_dir()]
        if missing:
            print(f"  {bank}: SKIPPED -- missing repo(s): {', '.join(missing)}")
            skipped += 1
            continue

        sources = sources_string(repos)
        subprocess.run(
            ["mergerfs", sources, str(mountpoint), "-o", MERGERFS_OPTS],
            check=True,
        )
        print(f"  {bank}: mounted ({len(repos)} repo(s))")
        mounted += 1

    print(f"\nDone: {mounted} mounted, {skipped} skipped")


def do_unmount() -> None:
    print("Unmounting mergerfs views...")
    for bank in sorted(BANK_REPOS):
        mountpoint = VIEW_ROOT / bank
        if is_mounted(mountpoint):
            subprocess.run(["fusermount", "-u", str(mountpoint)], check=True)
            print(f"  {bank}: unmounted")
    print("Done.")


def do_status() -> None:
    print("mergerfs mount status:\n")
    print(f"  {'Bank':<15} {'Status':<10} Sources")
    print(f"  {'----':<15} {'------':<10} -------")
    for bank in sorted(BANK_REPOS):
        repos = BANK_REPOS[bank]
        mountpoint = VIEW_ROOT / bank
        if is_mounted(mountpoint):
            print(f"  {bank:<15} {'MOUNTED':<10} {len(repos)} repo(s)")
        else:
            print(f"  {bank:<15} {'not mounted':<10}")


def do_fstab() -> None:
    print("# mergerfs union mounts for TalkBank data repos")
    print("# Add these lines to /etc/fstab on talkbank.org")
    print(f"# Generated by {Path(__file__).name}")
    print()
    for bank in sorted(BANK_REPOS):
        sources = sources_string(BANK_REPOS[bank])
        mountpoint = VIEW_ROOT / bank
        print(f"{sources} {mountpoint} fuse.mergerfs {MERGERFS_OPTS} 0 0")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Set up mergerfs union mounts for TalkBank data repos",
    )
    parser.add_argument(
        "action",
        choices=["mount", "unmount", "status", "fstab"],
        help="mount: create all mounts, unmount: remove all mounts, "
        "status: show mount status, fstab: print /etc/fstab entries",
    )
    args = parser.parse_args()

    if args.action == "mount":
        do_mount()
    elif args.action == "unmount":
        do_unmount()
    elif args.action == "status":
        do_status()
    elif args.action == "fstab":
        do_fstab()


if __name__ == "__main__":
    main()
